### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by nico00pruebas** [nicoambrosis/Git-and-Github-First-Steps#1]
Este es solo un issue de prueba.
Fue realizado durante el curso [Git y GitHub completo desde cero](https://www.udemy.com/course/git-y-github-completo-desde-cero/learn/lecture/5624388#questions).

No se reporta ningun problema con este repositorio

**Comment by nicoambrosis** [comment]
Respuesta al issue. Nada que responder. Es solo una respuesta de prueba
